RULE_MIN_LENGTH = 0
RULE_MAX_LENGTH = 1
RULE_MIN_WIDTH = 2
RULE_MAX_WIDTH = 3
RULE_MIN_HEIGTH = 4
RULE_MAX_HEIGTH = 5

ERROR_RULE = [  "PRZEKROCZONO MINIMALNĄ DŁUGOŚĆ",
                "PRZEKROCZONO MAKSYMALNĄ DŁUGOŚĆ",
                "PRZEKROCZONO MINIMALNĄ SZEROKOŚĆ",
                "PRZEKROCZONO MAKSYMALNĄ SZEROKOŚĆ",
                "PRZEKROCZONO MINIMALNĄ WYSOKOŚĆ",
                "PRZEKROCZONO MAKSYMALNĄ WYSOKOŚĆ"]