RULE_MIN_LENGTH = 0
RULE_MAX_LENGTH = 1
RULE_MIN_WIDTH = 2
RULE_MAX_WIDTH = 3
RULE_MIN_HEIGTH = 4
RULE_MAX_HEIGTH = 5
RULE_EXACT_HEIGTH = 6

ERROR_RULE = [  "PRZEKROCZONO MINIMALNĄ DŁUGOŚĆ",
                "PRZEKROCZONO MAKSYMALNĄ DŁUGOŚĆ",
                "PRZEKROCZONO MINIMALNĄ SZEROKOŚĆ",
                "PRZEKROCZONO MAKSYMALNĄ SZEROKOŚĆ",
                "PRZEKROCZONO MINIMALNĄ WYSOKOŚĆ",
                "PRZEKROCZONO MAKSYMALNĄ WYSOKOŚĆ",
                "NIEDOPUSZCZALNA WYSOKOŚĆ, AKCEPTOWALNE WARTOŚCI"]

MATERIAL_NONE = 0
MATERIAL_PLATE = 1
MATERIAL_METAL = 2
MATERIAL_GLASS = 3
MATERIAL_MDF19 = 4

MATERIAL_NAME = [   "NIEOKREŚLONE",
                    "PŁYTA LAMINOWANA",
                    "METAL",
                    "SZKŁO",
                    "PŁľYTA MDF #19"]

SLIDE_NONE = 0
SLIDE_PK44 = 1
SLIDE_PK05 = 2
SLIDE_PK06 = 3